import "~/styles/globals.css";

import { Commissioner } from "next/font/google";

const inter = Commissioner({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Crowdfunding Product Page",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/images/favicon-32x32.png" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>{children}</body>
    </html>
  );
}
